#!/usr/bin/env zsh
# zdot_reclone_plugins: Remove and re-clone all plugins

zdot_reclone_plugins() {
    local cache_dir
    zstyle -s ':zdot:plugins' directory cache_dir
    cache_dir=${cache_dir:-${XDG_CACHE_HOME:-${HOME}/.cache}/zdot/plugins}
    
    zdot_report "Removing plugin cache at $cache_dir..."
    rm -rf "$cache_dir"
    
    # Reset plugin state so they'll be re-cloned on next shell start
    unset _ZDOT_PLUGINS_INITIALIZED 2>/dev/null
    
    zdot_info "Cache removed. Plugins will be re-cloned on next shell start."
}
