#!/usr/bin/env zsh
# Basic ripgrep with fzf

fzf_rg() {
    local enter_bind=${1:-"enter:accept"}
    rg --color=always --line-number --no-heading --smart-case "${@[2,-1]:-}" |
        fzf --ansi \
            --color "hl:-1:underline,hl+:-1:underline:reverse" \
            --delimiter : \
            --preview 'bat --color=always {1} --highlight-line {2}' \
            --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
            --bind "${enter_bind}"
}
