#!/usr/bin/env zsh
# upload or replace file item in vault
# Requires _ZDOT_OP_ACTIVE=1 (service account configured)

op_upsert_file() {
    local vault="$1"
    local item_name="$2"
    local file_path="$3"
    
    if op document get "$item_name" --vault="$vault" &>/dev/null; then
        echo "Updating existing item: $item_name"
        op document edit "$item_name" "$file_path" --vault="$vault"
    else
        echo "Creating new item: $item_name"
        op document create  "$file_path" --vault="$vault" --title="$item_name"
    fi
}
