#!/usr/bin/env zsh
# core/completions: Completion registration API
# Provides lightweight registration for file-based and live completions

# ============================================================================
# Completion Registration API
# ============================================================================

# Register a completion to be generated by refresh_completions
# Usage: zdot_completion_register_file <command> <generate-command> [dest-dir]
# Example: zdot_completion_register_file "gh" "gh completion -s zsh"
# Example: zdot_completion_register_file "gh" "gh completion -s zsh" "/custom/path"
zdot_completion_register_file() {
    local cmd="$1"
    local gen_cmd="$2"
    local dest_dir="$3"
    if [[ -z "$dest_dir" ]]; then
        _zdot_completions_dir
        dest_dir="$REPLY"
    fi

    if [[ -z "$cmd" || -z "$gen_cmd" ]]; then
        zdot_error "zdot_completion_register_file: command and generate-command required"
        return 1
    fi

    _ZDOT_COMPLETION_CMDS+=("$cmd")
    _ZDOT_COMPLETION_GEN[$cmd]="$gen_cmd"
    _ZDOT_COMPLETION_DEST[$cmd]="$dest_dir"
}

# Register a completion function to run live during init
# Usage: zdot_completion_register_live <function-name>
zdot_completion_register_live() {
    local func="$1"

    if [[ -z "$func" ]]; then
        zdot_error "zdot_completion_register_live: function name required"
        return 1
    fi

    _ZDOT_COMPLETION_LIVE+=("$func")
}
