#!/usr/bin/env zsh
# Refresh MCP servers configuration from 1Password
# Requires _ZDOT_OP_ACTIVE=1 (service account configured)

function refresh_gcert_secrets {
    [[ $_ZDOT_OP_ACTIVE -ne 1 ]] && return 1

    local secrets_src_dir secrets_cache secrets_mcp_dir
    _mcp_get_secrets_mcp_dirs
        
    op_get_gmail_certs
    local -A gmail_certs=("${reply[@]}")
    
    op_setup_gcert_certificate

    echo ${gmail_certs}

    for account secretname in ${(kv)gmail_certs}; do
        local domain="${${account#*@}%%.*}"
        local certfile="${domain}-google-cert.json"
        local gmail_mcp_dir="${secrets_mcp_dir}/gmail-mcp"
        local domain_mcp_dir="${gmail_mcp_dir}/${domain}"
        local certfile_out="${domain_mcp_dir}/credentials.json"
        local certfile_dest="${domain_mcp_dir}/${certfile}"

        # Top level cert into domain dir
        [[ -L "${domain_mcp_dir}/gcp-oauth.keys.json" ]] && rm "${domain_mcp_dir}/gcp-oauth.keys.json"
        ln -s "${gmail_mcp_dir}/gcp-oauth.keys.json" "${domain_mcp_dir}/gcp-oauth.keys.json"

        op_download_file "API" "${secretname}" "${domain_mcp_dir}"

        [[ -L "${certfile_out}" ]] && rm "${certfile_out}"
        ln -s "${certfile_dest}" "${certfile_out}"
    done
}
