#!/usr/bin/env zsh
# Get 1Password config directory path
# Returns directory path via stdout

function op_get_config_dir {
    local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/op"

    # If running as sudo, use real user's config
    if [[ -n "${SUDO_USER}" && -n "${REAL_HOME}" ]]; then
        echo "${REAL_HOME}/.config/op"
    else
        echo "$config_dir"
    fi
}
