#!/usr/bin/env zsh
# Refresh shell secrets from 1Password
# Requires _ZDOT_OP_ACTIVE=1 (service account configured)

function refresh_shell_secrets {
    [[ $_ZDOT_OP_ACTIVE -ne 1 ]] && return 1

    local secrets_src_dir secrets_cache
    _op_get_secrets_dirs

    # Get op config
    local -a op_config
    local op_config_dir
    op_config_dir=$(op_get_config_dir)
    op_config=("${(@f)$(op_get_config_args)}")

    if [[ ! -f "${secrets_src_dir}/secrets.zsh" ]]; then
        return 1
    fi

    local op_output
    op_output=$(op ${op_config} inject --force --in-file "${secrets_src_dir}/secrets.zsh" --out-file "${secrets_cache}/${USER}.secrets.zsh" 2>&1)
    if [[ $? -eq 0 ]]; then
        source "${secrets_cache}/${USER}.secrets.zsh"
        return 0
    else
        zdot_warn "secrets: failed to refresh shell secrets"
        [[ -n "$op_output" ]] && zdot_error "secrets: $op_output"
        return 1
    fi
}
