#!/usr/bin/env zsh
# Get 1Password setup for gcerts
# Returns directory path via stdout

function op_get_gmail_certs {
    reply=(
        george@george-graphics.co.uk "GmailCertGeorgeGraphics"
        george@georgeharker.com "GMailCertGeorgeHarker"
        george@infinitevariation.com "GMailCertInfiniteVariation"
    )
}


