#!/usr/bin/env zsh
# Get gcert certificate from 1password
# Requires _ZDOT_OP_ACTIVE=1 (service account configured)

function op_setup_gcert_certificate {
    [[ $_ZDOT_OP_ACTIVE -ne 1 ]] && return 1

    local secrets_src_dir secrets_cache secrets_mcp_dir
    _mcp_get_secrets_mcp_dirs

    op_download_file "API" "GoogleComputeOAuth" "${secrets_mcp_dir}/gmail-mcp"
}

